import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { access, copyFile, readFile } from "fs/promises";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Copy the build artifacts into the running Obsidian plugin folder so changes
// take effect on reload. Resolves to the vault plugin dir when this repo lives
// inside the vault (../../.obsidian/plugins/<id>), and is skipped silently when
// that folder is absent (e.g. CI or a clone outside the vault). Override with
// OBSIDIAN_PLUGIN_DIR.
const vaultPluginDir =
	process.env.OBSIDIAN_PLUGIN_DIR
	|| path.resolve("../../.obsidian/plugins/native-powerpoint-doc-editor");
const filesToDeploy = ["main.js", "styles.css", "manifest.json"];

const deployToVaultPlugin = {
	name: "deploy-to-vault-plugin",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;

			try {
				await access(vaultPluginDir);
			} catch {
				return;
			}

			await Promise.all(
				filesToDeploy.map(async (file) => {
					try {
						await copyFile(path.resolve(file), path.join(vaultPluginDir, file));
					} catch (error) {
						console.warn(`[deploy] could not copy ${file}: ${error.message}`);
					}
				})
			);
			console.log(`[deploy] synced ${filesToDeploy.join(", ")} -> ${vaultPluginDir}`);
		});
	}
};

const inlinePptxSvgWasmPlugin = {
	name: "inline-pptx-svg-wasm",
	setup(build) {
		build.onLoad({ filter: /pptx-renderer\.js$/ }, async (args) => {
			const normalizedPath = args.path.replace(/\\/g, "/");
			if (!normalizedPath.endsWith("/node_modules/pptx-svg/dist/pptx-renderer.js")) {
				return undefined;
			}

			const source = await readFile(args.path, "utf8");

			let contents = source.replace(
				"const DEFAULT_WASM_URL = new URL('./main.wasm', import.meta.url).href;",
				"const DEFAULT_WASM_URL = undefined;"
			);

			// Teach PptxRenderer to run on the pure-JS engine fallback (used when the
			// runtime lacks WebAssembly GC). `initJsBackend` reuses the existing host
			// FFI (buildImportObject) and stores the JS engine exports where the Wasm
			// instance normally lives, so every `this.exports.*` call works unchanged.
			// The `exports` getter re-publishes this instance's FFI on `globalThis`
			// before each (synchronous) call, keeping multiple open presentations
			// isolated from one another.
			const getterAnchor = "    get exports() {\n        if (!this.wasm)";
			if (!contents.includes(getterAnchor)) {
				throw new Error(
					"[inline-pptx-svg-wasm] could not find the `exports` getter to patch — " +
					"pptx-svg internals changed; update esbuild.config.mjs."
				);
			}
			contents = contents.replace(
				getterAnchor,
				"    initJsBackend(engine) {\n" +
				"        this.__jsFfi = this.buildImportObject().pptx_ffi;\n" +
				"        this.wasm = { exports: engine };\n" +
				"        globalThis.pptx_ffi = this.__jsFfi;\n" +
				"    }\n" +
				"    get exports() {\n" +
				"        if (this.__jsFfi)\n" +
				"            globalThis.pptx_ffi = this.__jsFfi;\n" +
				"        if (!this.wasm)"
			);

			return { contents, loader: "js" };
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	// The pure-JS PPTX engine fallback (src/vendor/pptx-js-engine.mjs) uses BigInt
	// literals. It only runs on Chromium that lacks WebAssembly GC (≈111–118), all
	// of which support BigInt natively (Chrome 67+), so don't down-level or warn.
	supported: { bigint: true },
	alias: {
		"@eigenpal/docx-editor-i18n/en": "./node_modules/@eigenpal/docx-editor-i18n/dist/en.mjs",
		"@eigenpal/docx-editor-i18n/he": "./node_modules/@eigenpal/docx-editor-i18n/dist/he.mjs",
		"@eigenpal/docx-editor-i18n/pl": "./node_modules/@eigenpal/docx-editor-i18n/dist/pl.mjs",
		"@eigenpal/docx-editor-i18n/pt-BR": "./node_modules/@eigenpal/docx-editor-i18n/dist/pt-BR.mjs",
		"@eigenpal/docx-editor-i18n/tr": "./node_modules/@eigenpal/docx-editor-i18n/dist/tr.mjs",
		"@eigenpal/docx-editor-i18n/zh-CN": "./node_modules/@eigenpal/docx-editor-i18n/dist/zh-CN.mjs",
		"@eigenpal/docx-editor-i18n": "./src/shims/docx-editor-i18n.ts",
		"jszip": "./node_modules/jszip/lib/index.js",
		"immediate": "./src/shims/immediate.cjs",
		"readable-stream": "./node_modules/jszip/lib/readable-stream-browser.js",
		"setimmediate": "./src/shims/setimmediate.ts",
		"stream": "./src/shims/stream.cjs",
	},
	loader: {
		".css": "text",
		".wasm": "binary",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [inlinePptxSvgWasmPlugin, deployToVaultPlugin],
	outdir: ".",
	entryNames: "[name]",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
