import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFile } from "fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const inlinePptxSvgWasmPlugin = {
	name: "inline-pptx-svg-wasm",
	setup(build) {
		build.onLoad({ filter: /pptx-renderer\.js$/ }, async (args) => {
			const normalizedPath = args.path.replace(/\\/g, "/");
			if (!normalizedPath.endsWith("/node_modules/pptx-svg/dist/pptx-renderer.js")) {
				return undefined;
			}

			const source = await readFile(args.path, "utf8");
			const contents = source.replace(
				"const DEFAULT_WASM_URL = new URL('./main.wasm', import.meta.url).href;",
				"const DEFAULT_WASM_URL = undefined;"
			);
			return { contents, loader: "js" };
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: {
		main: "src/main.ts",
		"docx-editor": "src/docxEditorChunk.ts",
	},
	bundle: true,
	external: [
		"./docx-editor.js",
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	alias: {
		"@eigenpal/docx-editor-i18n/en": "./node_modules/@eigenpal/docx-editor-i18n/dist/en.mjs",
		"@eigenpal/docx-editor-i18n/he": "./node_modules/@eigenpal/docx-editor-i18n/dist/he.mjs",
		"@eigenpal/docx-editor-i18n/pl": "./node_modules/@eigenpal/docx-editor-i18n/dist/pl.mjs",
		"@eigenpal/docx-editor-i18n/pt-BR": "./node_modules/@eigenpal/docx-editor-i18n/dist/pt-BR.mjs",
		"@eigenpal/docx-editor-i18n/tr": "./node_modules/@eigenpal/docx-editor-i18n/dist/tr.mjs",
		"@eigenpal/docx-editor-i18n/zh-CN": "./node_modules/@eigenpal/docx-editor-i18n/dist/zh-CN.mjs",
		"@eigenpal/docx-editor-i18n": "./src/shims/docx-editor-i18n.ts",
		"jszip": "./node_modules/jszip/lib/index.js",
		"immediate": "./src/shims/immediate.cjs",
		"readable-stream": "./node_modules/jszip/lib/readable-stream-browser.js",
		"setimmediate": "./src/shims/setimmediate.ts",
	},
	loader: {
		".css": "text",
		".wasm": "binary",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [inlinePptxSvgWasmPlugin],
	outdir: ".",
	entryNames: "[name]",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
